version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kakon114

  express-app:
    build:
      context: teebay_be
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:kakon114@postgres:5432/postgres
      PORT: 4000
      JWT_SECRET: 123secret321

  frontend:
    build:
      context: teebay_fe
      args:
        - VITE_BASE_URL=http://localhost:4000
    ports:
      - "8080:8080"
    depends_on:
      - express-app
    environment:
      VITE_BASE_URL: http://localhost:4000

volumes:
  postgres-data:
